"""inicializandonovamente

Revision ID: ab47c631984a
Revises: 43b51c1a4e46
Create Date: 2023-12-17 23:06:17.763668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab47c631984a'
down_revision = '43b51c1a4e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sexo', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('data', sa.String(length=100), nullable=True))
        batch_op.drop_column('email')
        batch_op.drop_column('senha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('data')
        batch_op.drop_column('sexo')
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###
